version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app_name"
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mariadb:10.4.8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes_from:
      - data
    ports:
      - "3306:3306"

volumes:
  bundle:
    driver: local
